# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bot.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbot.proto\x12\x03\x62ot\"!\n\x0eMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x0fMessageResponse\x12\x10\n\x08response\x18\x01 \x01(\t2C\n\x07\x43\x61llBot\x12\x38\n\x0bSendMessage\x12\x13.bot.MessageRequest\x1a\x14.bot.MessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=18
  _globals['_MESSAGEREQUEST']._serialized_end=51
  _globals['_MESSAGERESPONSE']._serialized_start=53
  _globals['_MESSAGERESPONSE']._serialized_end=88
  _globals['_CALLBOT']._serialized_start=90
  _globals['_CALLBOT']._serialized_end=157
# @@protoc_insertion_point(module_scope)
